name: Update Site
on: [push, repository_dispatch]

jobs:
  build:
    name: Contentful Access Token
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env: 
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
